-- 0. Crear tablas faltantes si no existen
CREATE TABLE IF NOT EXISTS public.events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  name TEXT NOT NULL,
  type TEXT,
  description TEXT
);

CREATE TABLE IF NOT EXISTS public.wellness_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  hrv FLOAT,
  rhr FLOAT,
  sleep_hours FLOAT,
  readiness_score INT
);

-- 1. Asegurar que las tablas tienen la columna user_id (por si ya existían pero les faltaba)
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.wellness_data ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;

-- 2. Activar RLS en todas las tablas clave
ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.planned_workouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wellness_data ENABLE ROW LEVEL SECURITY;

-- 3. Crear políticas para activities
DROP POLICY IF EXISTS "Users can manage their own activities" ON public.activities;
CREATE POLICY "Users can manage their own activities"
  ON public.activities
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- 4. Crear políticas para planned_workouts
DROP POLICY IF EXISTS "Users can manage their own planned workouts" ON public.planned_workouts;
CREATE POLICY "Users can manage their own planned workouts"
  ON public.planned_workouts
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- 5. Crear políticas para events
DROP POLICY IF EXISTS "Users can manage their own events" ON public.events;
CREATE POLICY "Users can manage their own events"
  ON public.events
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- 6. Crear políticas para wellness_data
DROP POLICY IF EXISTS "Users can manage their own wellness data" ON public.wellness_data;
CREATE POLICY "Users can manage their own wellness data"
  ON public.wellness_data
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);
